# .github/workflows/push-trigger.yml
name: Trigger Workflow in Another Repo with Date

on:
  push:
    branches:
      - 2022-01-16

jobs:
  trigger-other-repo-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/rstats-on-nix/build_tree/dispatches \
          -d '{
            "event_type": "trigger-workflow",
            "client_payload": {
              "ref_name": "${{ github.ref_name }}"
            }
          }'
